### ISSUE TITLE
Are conflicts possible?

### ISSUE THREAD

**Issue by remram44** [remram44/gitobox#2]
Git doesn't conflict, because branch updates are atomic and commits have explicit parents. But the watched folder doesn't have that.

If a change happens in Git, the files will be put inside the directory. If a change happens on DropBox at the same time, DropBox will become conflicted; there is no way to prevent that (DropBox has no atomic operations). There should be a check for that, to create a Git commit with the conflicted files that DropBox will create, so that we can resolve it from either DropBox or Git (and we can then rebase to make these disappear from the Git history).

If a change happens in the folder, gitobox will wait for a certain amount of seconds and then try to commit that. During that time, we need to make sure that we disallow changes in the Git repository by grabbing the lock as well (not just when the timer expire, for the time of the commit operation).

**Comment by JosuaKrause** [comment]
A possible way to avoid conflicts or let them happen only on the git side is to stop syncing to dropbox whenever something interesting is done (ie. committing) and checking the sync status of a file before overwriting. This can be done with the [CLI for dropbox](http://www.dropboxwiki.com/tips-and-tricks/using-the-official-dropbox-command-line-interface-cli#Installation) and the commands [`start`, `stop`, `filestatus`, and `ls`](http://www.dropboxwiki.com/tips-and-tricks/using-the-official-dropbox-command-line-interface-cli#HELP). However, this still doesn't solve conflicts on dropbox's side completely since dropbox's only mechanism to deal with this is to create multiple conflicted files which can only be detected by their name (ie. `foo's conflicted copy`).

**Comment by remram44** [comment]
Dropbox is not instantaneous so conflicts can still happen :cry:

Worst case is, other dropbox user is offline; he'll conflict when he comes back on, and I have no way to avoid it.
